apiVersion: v1
kind: Pod
metadata:
  name: s3-test
spec:
  containers:
    - name: app
      image: amazonlinux
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]
      volumeMounts:
        - name: s3-storage
          mountPath: /mnt/data
  volumes:
    - name: s3-storage
      persistentVolumeClaim:
        claimName: s3-pvc
